local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node

return {
    s("report", {
        t({
            "\\documentclass[a4paper,12pt,openany]{ltjsreport}",
            "",
            "% ============================================================",
            "% フォント設定",
            "% ============================================================",
            "\\usepackage{luatexja-fontspec}",
            "",
            "\\setmainfont{TeX Gyre Termes}",
            "\\setsansfont{TeX Gyre Heros}",
            "\\setmainjfont[",
            "  BoldFont=Harano Aji Mincho Bold,",
            "  ItalicFont=Harano Aji Mincho,",
            "  BoldItalicFont=Harano Aji Mincho Bold",
            "]{Harano Aji Mincho}",
            "",
            "% ============================================================",
            "% レイアウト",
            "% ============================================================",
            "\\usepackage[top=25mm,bottom=25mm,left=25mm,right=25mm,bindingoffset=0mm]{geometry}",
            "\\usepackage{indentfirst}",
            "",
            "% ============================================================",
            "% 汎用パッケージ",
            "% ============================================================",
            "\\usepackage{pdfpages}",
            "\\usepackage{siunitx}",
            "\\usepackage{enumitem}",
            "\\usepackage{graphicx}",
            "\\usepackage{amsmath}",
            "\\usepackage[normalem]{ulem}",
            "\\usepackage{url}",
            "\\usepackage{float}",
            "",
            "% ============================================================",
            "% 表組み・図",
            "% ============================================================",
            "\\usepackage{makecell}",
            "\\usepackage{hhline}",
            "\\usepackage{tabularray}",
            "\\usepackage{diagbox}",
            "\\usepackage{tikz}",
            "\\usepackage[framemethod=TikZ]{mdframed}",
            "\\makeatletter",
            "\\def\\caption@documentclass{standard}",
            "\\makeatother",
            "\\usepackage{caption}",
            "\\usepackage{pifont}",
            "\\usepackage{varwidth}",
            "",
            "% ============================================================",
            "% 見出しスタイル・カラー・コードリスト",
            "% ============================================================",
            "\\usepackage{titlesec}",
            "\\usepackage[dvipsnames]{xcolor}",
            "\\usepackage{listings}",
            "",
            "% ============================================================",
            "% 参考文献",
            "% ============================================================",
            "\\usepackage[",
            "  backend=biber,",
            "  style=numeric,",
            "  sorting=none,",
            "  date=iso,",
            "  urldate=iso,",
            "  seconds=true,",
            "  bibencoding=utf8",
            "]{biblatex}",
            "\\addbibresource{ref/references.bib}",
            "",
            "\\DeclareFieldFormat*{title}{#1}",
            "\\DeclareFieldFormat*{journaltitle}{#1}",
            "\\DeclareFieldFormat*{booktitle}{#1}",
            "\\DeclareFieldFormat{url}{\\url{#1}}",
            "\\DefineBibliographyStrings{english}{",
            "  urlseen = {参照},",
            "}",
            '\\DeclareFieldFormat[article,inproceedings,misc]{title}{"#1"}',
            '\\DeclareFieldFormat[book,inbook]{title}{"#1"}',
            "",
            "% ============================================================",
            "% キャプション日本語化",
            "% ============================================================",
            "\\captionsetup[figure]{name=図}",
            "\\captionsetup[table]{name=表}",
            "\\captionsetup{labelsep=colon}",
            "",
            "% ============================================================",
            "% 図表・数式番号形式",
            "% ----",
            "% \\chapter なし（図1 形式）→ 下記ブロックをそのまま使用",
            "% \\chapter あり（図1.1 形式）→ 下記ブロックを丸ごとコメントアウト",
            "% ============================================================",
            "\\makeatletter",
            "\\@removefromreset{section}{chapter}",
            "\\@removefromreset{figure}{chapter}",
            "\\@removefromreset{table}{chapter}",
            "\\@removefromreset{equation}{chapter}",
            "\\makeatother",
            "\\renewcommand{\\thesection}{\\arabic{section}}",
            "\\renewcommand{\\thefigure}{\\arabic{figure}}",
            "\\renewcommand{\\thetable}{\\arabic{table}}",
            "\\renewcommand{\\theequation}{\\arabic{equation}}",
            "% ============================================================",
            "",
            "% ============================================================",
            "% 見出しフォントサイズ・スペーシング",
            "% ============================================================",
            "\\titleformat{\\chapter}[block]",
            "  {\\fontsize{16pt}{18pt}\\selectfont\\bfseries}",
            "  {第\\thechapter 章\\quad}",
            "  {0pt}{}",
            "\\titlespacing*{\\chapter}{0pt}{20pt}{15pt}",
            "",
            "\\titleformat{\\section}",
            "  {\\fontsize{14pt}{16pt}\\selectfont\\bfseries}",
            "  {\\thesection.\\quad}",
            "  {0pt}{}",
            "\\titlespacing*{\\section}{0pt}{15pt}{10pt}",
            "",
            "\\titleformat{\\subsection}",
            "  {\\fontsize{12pt}{14pt}\\selectfont\\bfseries}",
            "  {\\thesubsection\\quad}",
            "  {0pt}{}",
            "\\titlespacing*{\\subsection}{0pt}{10pt}{5pt}",
            "",
            "\\titleformat{\\subsubsection}",
            "  {\\normalsize\\bfseries}",
            "  {\\thesubsubsection\\quad}",
            "  {0pt}{}",
            "",
            "\\setcounter{secnumdepth}{3}",
            "",
            "% ============================================================",
            "% listings カラー定義",
            "% ============================================================",
            "\\definecolor{codebg}{RGB}{245,245,245}",
            "\\definecolor{identifiercolor}{RGB}{7,54,66}",
            "\\definecolor{commentcolor}{RGB}{88,110,117}",
            "\\definecolor{framecolor}{RGB}{200,200,200}",
            "\\definecolor{keywordcolor}{RGB}{38,139,210}",
            "\\definecolor{builtincolor}{RGB}{133,153,0}",
            "\\definecolor{stringcolor}{RGB}{42,161,152}",
            "",
            "% ============================================================",
            "% listings スタイル定義",
            "% ============================================================",
            "\\lstdefinestyle{codestyle}{",
            "  backgroundcolor=\\color{codebg},",
            "  basicstyle=\\linespread{1.1}\\small\\ttfamily\\color{identifiercolor},",
            "  frame=single,",
            "  framerule=0.5pt,",
            "  rulecolor=\\color{framecolor},",
            "  breaklines=true,",
            "  showstringspaces=false,",
            "  numbers=left,",
            "  xleftmargin=2em,",
            "  keywordstyle=\\color{keywordcolor}\\bfseries,",
            "  stringstyle=\\color{stringcolor},",
            "  commentstyle=\\color{commentcolor}\\itshape,",
            "  numberstyle=\\normalsize\\color{black},",
            "}",
            "",
            "\\lstdefinestyle{python}{",
            "  style=codestyle,",
            "  language=Python,",
            "  morekeywords=[2]{self,True,False,None,print,range,len,dict,list,set,zip,",
            "    int,str,float,max,min,open,round,tuple,Exception,ValueError,",
            "    FileNotFoundError,__name__},",
            "  keywordstyle=[2]\\color{builtincolor},",
            "}",
            "",
            "\\lstdefinestyle{cpp}{",
            "  style=codestyle,",
            "  language=C++,",
            "  morekeywords=[2]{",
            "    nullptr,bool,true,false,",
            "    uint8_t,uint16_t,uint32_t,",
            "    int8_t,int16_t,int32_t,",
            "    size_t,String,",
            "    setup,loop,",
            "    pinMode,digitalWrite,digitalRead,",
            "    analogRead,analogWrite,",
            "    delay,delayMicroseconds,",
            "    millis,micros,",
            "    HIGH,LOW,INPUT,OUTPUT,INPUT_PULLUP,",
            "    Serial,begin,print,println,write,available,read,",
            "    SoftwareSerial",
            "  },",
            "  keywordstyle=[2]\\color{builtincolor},",
            "}",
            "",
            "\\lstset{style=python}",
            "",
            "% コードブロックの日本語化",
            "\\renewcommand{\\lstlistingname}{コード}",
            "\\renewcommand{\\lstlistlistingname}{コード一覧}",
            "",
            "% ============================================================",
            "% siunitx",
            "% ============================================================",
            "\\sisetup{",
            "  detect-all,",
            "  mode=math",
            "}",
            "",
            "% ============================================================",
            "% hyperref",
            "% ============================================================",
            "\\usepackage{hyperref}",
            "\\hypersetup{",
            "  colorlinks=true,",
            "  linkcolor=black,",
            "  urlcolor=black,",
            "  citecolor=black,",
            "  bookmarksnumbered=true,",
            "  pdfborder={0 0 0},",
            "  pdfencoding=auto,",
            "  pdftitle={",
        }),
        t("レポート"),
        t({
            "},",
            "  pdfauthor={中山 将吾",
        }),
        t({
            "}",
            "}",
            "",
            "\\begin{document}",
            "",
            "\\setcounter{page}{1}",
            "",
            "% ============================================================",
            "% 表紙（どちらか一方を有効化）",
            "% ============================================================",
            "",
            "% -- 指定表紙PDFを使う場合（通常はこちら） --",
            "\\includepdf{./cover.pdf}",
            "",
            "% -- 自作表紙を使う場合はコメントを外す --",
            "% \\begin{titlepage}",
            "%   \\vspace*{\\stretch{1.0}}",
            "%   \\begin{flushright}",
            "%     \\large{提出日：YYYY年MM月DD日}",
            "%   \\end{flushright}",
            "%   \\vspace*{\\stretch{2.3}}",
            "%   \\begin{center}",
            "%     {\\huge 授業名} \\\\",
            "%     {\\vspace{1cm}}",
            "%     {\\huge No.X}",
            "%   \\end{center}",
            "%   \\vspace*{\\stretch{3.0}}",
            "%   \\begin{center}",
            "%     {\\large 所属：学科・学年} \\\\",
            "%     \\vspace{0.5cm}",
            "%     {\\large 学籍番号：XXXXXXX}\\\\",
            "%     \\vspace{0.5cm}",
            "%     {\\large 氏名：氏名}",
            "%   \\end{center}",
            "%   \\vspace*{\\stretch{1.0}}",
            "% \\end{titlepage}",
            "",
            "\\section{目的}",
            "",
        }),
        i(0),
        t({
            "",
            "",
            "\\section{原理}",
            "",
            "\\section{使用機器}",
            "",
            "\\section{実験方法}",
            "",
            "\\section{結果}",
            "",
            "\\section{考察}",
            "",
            "\\section{結論}",
            "",
            "\\printbibliography[title=参考文献]",
            "",
            "\\end{document}",
        }),
    }),

    -- 図挿入
    s("fig", {
        t({
            "\\begin{figure}[H]",
            "  \\centering",
            "  \\includegraphics[width=",
        }),
        i(1, "0.8"),
        t("\\linewidth]{"),
        i(2, "filename"),
        t({
            "}",
            "  \\caption{",
        }),
        i(3, "キャプション"),
        t({
            "}",
            "  \\label{fig:",
        }),
        i(4, "label"),
        t({
            "}",
            "\\end{figure}",
        }),
    }),

    -- 表挿入
    s("tab", {
        t({
            "\\begin{table}[H]",
            "  \\centering",
            "  \\caption{",
        }),
        i(1, "キャプション"),
        t({
            "}",
            "  \\label{tab:",
        }),
        i(2, "label"),
        t({
            "}",
            "  \\begin{tabular}{",
        }),
        i(3, "cc"),
        t({
            "}",
            "    \\hline",
            "    ",
        }),
        i(4, "列1 & 列2"),
        t({
            " \\\\",
            "    \\hline",
            "    ",
        }),
        i(0),
        t({
            " \\\\",
            "    \\hline",
            "  \\end{tabular}",
            "\\end{table}",
        }),
    }),

    -- 数式（番号なし）
    s("eq", {
        t({
            "\\begin{align*}",
            "    ",
        }),
        i(0),
        t({
            "",
            "\\end{align*}",
        }),
    }),

    -- 数式（番号あり・ラベル付き）
    s("eqn", {
        t({
            "\\begin{align}",
            "    ",
        }),
        i(1),
        t({
            "",
            "  \\label{eq:",
        }),
        i(2, "label"),
        t({
            "}",
            "\\end{align}",
        }),
    }),

    -- コードブロック
    s("code", {
        t("\\begin{lstlisting}[style="),
        i(1, "python"),
        t(", caption={"),
        i(2, "キャプション"),
        t("}, label={code:"),
        i(3, "label"),
        t({
            "}]",
            "",
        }),
        i(0),
        t({
            "",
            "\\end{lstlisting}",
        }),
    }),

    -- 修飾系
    s("vec", { t("\\vec{"), i(1), t("}") }),
    s("hat", { t("\\hat{"), i(1), t("}") }),
    s("bar", { t("\\bar{"), i(1), t("}") }),
    s("tilde", { t("\\tilde{"), i(1), t("}") }),
    s("dot", { t("\\dot{"), i(1), t("}") }),
    s("ddot", { t("\\ddot{"), i(1), t("}") }),
    s("bm", { t("\\boldsymbol{"), i(1), t("}") }),

    -- 分数・根号
    s("frac", { t("\\frac{"), i(1), t("}{"), i(2), t("}") }),
    s("dfrac", { t("\\dfrac{"), i(1), t("}{"), i(2), t("}") }),
    s("sqrt", { t("\\sqrt{"), i(1), t("}") }),

    -- テキスト・色
    s("txt", { t("\\text{"), i(1), t("}") }),
    s("color", { t("\\textcolor{"), i(1), t("}{"), i(2), t("}") }),

    -- 積分
    s("int", { t("\\int_{"), i(1), t("}^{"), i(2), t("}"), i(3) }),
    s("iint", { t("\\iint_{"), i(1), t("}"), i(2) }),
    s("oint", { t("\\oint_{"), i(1), t("}"), i(2) }),
}
